export var categorias = [
    {
        id: 1,
        nombre: "Deportes",
        fecha: new Date(),
    },
];

//

export var juegos = [
    {
        image: "https://cdn.akamai.steamstatic.com/steam/apps/1811260/capsule_616x353.jpg?t=1677074188",
        nombre: "Fifa 23",
        genero: "Acción",
        plataforma: "PC",
        desarrollador: "Mi empresa",
        lanzamiento: "2023",
        duracion: "10 horas",
        jugadores: "1 jugador",
        idiomas: ["Español", "Inglés", "Francés"],
        niveles: ["Fácil", "Intermedio", "Difícil"],
        historia: "Una historia épica de aventuras y peligros",
        personajes: ["Protagonista", "Antagonista", "Aliados", "Enemigos"],
        objetos: ["Armas", "Poderes", "Vehículos", "Consumibles"],
        enemigos: ["Básicos", "Jefes de nivel", "Finales"],
        mundos: ["Bosques", "Ciudades", "Desiertos", "Montañas"],
        objetivos: ["Misiones principales", "Misiones secundarias", "Logros"],
        modo_multijugador: false,
        modo_en_linea: false,
        tutorial: true,
        opciones: ["Sonido", "Gráficos", "Controles"],
        dificultad: 2,
        categoriaId: 1,
    },
    {
        image: "https://i.blogs.es/6bfe40/forzahorizon5_launch_preview-04_16x9_wm/840_560.jpeg",
        nombre: "Forza Horizon 5",
        genero: "Acción",
        plataforma: "PC",
        desarrollador: "Mi empresa",
        lanzamiento: "2023",
        duracion: "10 horas",
        jugadores: "1 jugador",
        idiomas: ["Español", "Inglés", "Francés"],
        niveles: ["Fácil", "Intermedio", "Difícil"],
        historia: "Una historia épica de aventuras y peligros",
        personajes: ["Protagonista", "Antagonista", "Aliados", "Enemigos"],
        objetos: ["Armas", "Poderes", "Vehículos", "Consumibles"],
        enemigos: ["Básicos", "Jefes de nivel", "Finales"],
        mundos: ["Bosques", "Ciudades", "Desiertos", "Montañas"],
        objetivos: ["Misiones principales", "Misiones secundarias", "Logros"],
        modo_multijugador: false,
        modo_en_linea: false,
        tutorial: true,
        opciones: ["Sonido", "Gráficos", "Controles"],
        dificultad: 2,
        categoriaId: 1,
    },
];
